config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :pets
  resources :pet_histories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :pets, dependent: :destroy

    def count_pets
        self.pets.count 
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
    has_many :pet_histories
    belongs_to :client

  def history_count
    self.pet_histories.count
  end

  def avg_weight
    if self.pet_histories.count > 0

      self.pet_histories.sum(:weight)/self.pet_histories.count

    else
      "Sin Historial"
    end
  end

  def avg_height
    if self.pet_histories.count > 0

      (self.pet_histories.sum(:height)/self.pet_histories.count).round(1)

    else
      "Sin Historial"
    end
  end

  def max_weight

    if self.pet_histories.count > 0

      self.pet_histories.maximum("weight")

    else
      "Sin Historial"
    end
  end

  def max_height
    if self.pet_histories.count > 0

      self.pet_histories.maximum("height")

    else
      "Sin Historial"
    end
  end

end

app/models/pet_history.rb
class PetHistory < ApplicationRecord
    belongs_to :pet

    def historial
        @historial = Pethistory.all
    end

    def pet_name
        @pet_name = Pet.find(self.pet_id).name
    end

    def owner
        @owner = Client.find(self.client_id).name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end
  
  # GET /clients/1 or /clients/1.json
  def show
    @pets = @client.pets
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Ingresado exitosamente." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Ingresado exitosamente." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Cliente eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :phone_number, :email)
    end
end

app/controllers/pet_histories_controller.rb
class PetHistoriesController < ApplicationController
  before_action :set_pet_history, only: %i[ :show, :edit, :update, :destroy ]

  # GET /pet_histories
  # GET /pet_histories.json
  def index
    
    @pet_histories = PetHistory.all
  
  end

  # GET /pet_histories/1
  # GET /pet_histories/1.json
  def show
    
    
  end

  # GET /pet_histories/new
  def new
    @pet_history = PetHistory.new
    @pets = Pet.all
   
  end

  # GET /pet_histories/1/edit
  def edit
    @pets = Pet.all
  end

  # POST /pet_histories
  # POST /pet_histories.json
  def create
    @pet_history = PetHistory.new(pet_history_params)
    #@pet_history.client_id = @pet_history.pet.client_id 

    respond_to do |format|
      if @pet_history.save
        format.html { redirect_to pet_history_url(@pet_history), notice: "Registro de historial creado con éxito." }
        format.json { render :show, status: :created, location: @pet_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_histories/1
  # PATCH/PUT /pet_histories/1.json
  def update
   
    respond_to do |format|
      if @pet_history.update(pet_history_params)
        format.html { redirect_to pet_history_url(@pet_history), notice: 'Historial agregado.' }
        format.json { render :show, status: :ok, location: @pet_history }
        
      else
        format.html { render :edit }
        format.json { render json: @pet_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_histories/1
  # DELETE /pet_histories/1.json
  def destroy
    @pet_history.destroy
    respond_to do |format|
      format.html { redirect_to pet_histories_url, notice: 'Historial eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_history
      @pet_history = PetHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_history_params
      params.require(:pet_history).permit(:weight, :heigth, :description, :pet_id, :client_id)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
    
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
    @client = Client.all
  end

  # GET /pets/1/edit
  def edit
    @client = Client.all
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Mascota creada.' }
        format.json { render :show, status: :created, location: @pet }
      else
        @client = Client.all
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Ingresado exitosamente.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Mascota eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :race, :birthdate, :client_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pet_histories_helper.rb
module PetHistoriesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Nombre:</strong>
    <%= client.name %>
  </p>

  <p>
    <strong>Número Telefónico:</strong>
    <%= client.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= client.email %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :telefono, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Mostrar este cliente", @client %> |
  <%= link_to "Eliminar", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-striped">
  <thead>
    <tr class="text-center">
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Email</th>
      <th>Mascotas</th>
      <th>Nombres</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody class="text-center">
    <% @clients.each do |client| %>
      <tr>
        <td><%= link_to client.name, client %></td>
        <td><%= client.phone_number %></td>
        <td><%= client.email %></td>
        <td><%= client.count_pets %></td>
        <td class="text-right">
          <% client.pets.each do |pet|%>
            <li> <%= link_to pet.name, pet %></li> 
          <% end %>
        </td>
        <td><%= link_to 'Editar', edit_client_path(client) %></td>
        <td><%= link_to 'Eliminar', client, method: :delete, data: { confirm: 'está seguro?' } %></td>
      </tr>
    <% end %>
 
 
  <%= link_to "Cliente Nuevo", new_client_path %>
    
  </tbody>
</table>

app/views/clients/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Volver a clientes", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="table table-bordered text-center">
  <thead class="bg-primary text-white">
    <tr>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @client.name %> </td>
      <td><%= @client.phone_number %> </td> 
      <td><%= @client.email %></td>
    </tr>
  </tbody>

</table>

<table class="table table-bordered text-center">
  <thead class="bg-primary text-white">
    <tr>
      <th>Nombre</th>
      <th>Altura Máx</th>
      <th>Peso Máx</th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.name %> </td>
        <td><%= pet.max_height %> </td>
        <td><%= pet.max_weight %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Volver', clients_path %>
<%= button_to "Eliminar", @client, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veterinario</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><h1>VETERINARIA</h1></a>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
       <%= link_to 'Inicio', root_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Nueva Mascota', new_pet_path, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Nuevo Cliente', clients_path, class:'nav-link'%>
      </li>
     
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pet_histories/_form.html.erb
<%= form_with(model: pet_history) do |form| %>
  <% if pet_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet_history.errors.count, "error") %> prohibited this pet_history from being saved:</h2>

      <ul>
        <% pet_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  

  <div>
    <%= form.label :peso, style: "display: block" %>
    <%= form.text_field :weight %>
  </div>

  <div>
    <%= form.label :altura, style: "display: block" %>
    <%= form.text_field :height %>
  </div>

  <div>
    <%= form.label :descripción, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pet_histories/_pet_history.html.erb
<div id="<%= dom_id pet_history %>">
  
  <p>
  <strong>Fecha:</strong>
    <%= pethistory.created_at %>
  </p>
  
  <p>
    <strong>Dueño:</strong>
    <%= pethistory.owner %>
  </p>
  
  <p>
    <strong>Mascota:</strong>
    <%= pethistory.pet_name %>
  </p>
  <p>
    <strong>Peso:</strong>
    <%= pet_history.weight %>
  </p>

  <p>
    <strong>Altura:</strong>
    <%= pet_history.height %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= pet_history.description %>
  </p>

</div>

app/views/pet_histories/edit.html.erb
<h1>Editar historial de la mascota</h1>

<%= render "form", pet_history: @pet_history %>

<br>


 <div>
   <%= link_to "Mostrar Historial", @pet_history %> |
   <%= link_to "Volver al historial", pet_histories_path %>
 </div>

app/views/pet_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Historial de la Mascota</h1>



<br>

<table class="table table-hover table-bordered">
  <thead class="text-center">
    <tr class="bg-primary text-white">
      <th>Nombre</th>
      <th>Peso</th>
      <th>Altura</th>
      <th>Descripción</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="text-center">
    <% @pet_histories.each do |pet_history| %>
      <tr>
      <td><%= link_to pet.name, pet %></td>
        <td><%= pet_history.weight %></td>
        <td><%= pet_history.heigth %></td>
        <td><%= pet_history.description %></td>

        # <td> <% pet_histories.pet.each do |pet_history| %>
        #   <li> <%= history.created_at%></li>

    <% end %>
        

       
        <td><%= link_to 'Mostrar', pet_pet_history_path(@pet,pet_history.id) %></td>
        <td><%= link_to 'Editar', edit_pet_pet_history_path(@pet,pet_history.id) %></td>
        <td><%= link_to 'Eliminar', pet_pet_history_path(@pet,pet_history.id), method: :delete, data: { confirm: 'Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to "Nuevo historial", new_pet_history_path %>

app/views/pet_histories/new.html.erb
<h1>Nuevo Historial de Mascota</h1>

<%= render "form", pet_history: @pet_history %>

<br>

<div>
  <%= link_to "Volver al historial", pet_histories_path %>
</div>

app/views/pet_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pet_history %>

<p>
  <strong>Peso:</strong>
  <%= @pet_history.weight %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @pet_history.heigth %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @pet_history.description %>
</p>


<div>
  <%= link_to "Editar", edit_pet_history_path(@pet_history) %> |
  <%= link_to "Volver", pet_histories_path %>

  <%= button_to "Eliminar", @pet_history, method: :delete, data: { confirm: 'Está seguro?' } %>
</div>

app/views/pets/_form.html.erb
<%= form_with(model: pet) do |form| %>
  <% if pet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
        <% pet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :raza, style: "display: block" %>
    <%= form.text_field :race %>
  </div>

  <div>
    <%= form.label :fecha_nacimiento, style: "display: block" %>
    <%= form.date_field :birthdate %>
  </div>

  <div>
    <%= form.collection_select :client_id, 
      @client,:id,:name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>">
  <p>
    <strong>Nombre:</strong>
    <%= pet.name %>
  </p>

  <p>
    <strong>Raza:</strong>
    <%= pet.race %>
  </p>

  <p>
    <strong>Fecha de Nacimiento:</strong>
    <%= pet.birthdate %>
  </p>

</div>

app/views/pets/edit.html.erb
<h1>Editar Mascota</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Mostrar esta mascota", @pet %> |
  <%= link_to "Volver", pets_path %>
</div>

app/views/pets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mascotas</h1>

<table class="table table-hover table-bordered">
  <thead class="text-center">
    <tr class="bg-primary text-white">
      <th>Nombre</th>
      <th>Raza</th>
      <th>Fecha de Nacimiento</th>
      <th>Dueño</th>
      <th>Visitas</th>
      <th>Registro de Visitas</th>

      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody class="text-center">
    <% @pets.each do |pet| %>
      <tr>
      <td><%= link_to pet.name, pet %></td>
        <td><%= pet.race %></td>
        <td><%= pet.birthdate %></td>
        <td><%= pet.client.name%></td>
        <td><%= pet.history_count%></td>
        
        <td>
        <% pet.pet_histories.each do |history|%>
          <li> <%= history.created_at%></li>

        <% end %>
        </td>
        <td><%= link_to 'Editar', edit_pet_path(pet) %></td>
        <td><%= link_to 'Eliminar', pet, method: :delete, data: { confirm: 'Está seguro?' } %></td>
        <td><%= link_to 'Nueva historia', new_pet_history_path(pet)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pets/new.html.erb
<h1>Nueva Mascota</h1>

<%= render "form", pet: @pet %>

<br>

<div>
  <%= link_to "Volver", pets_path %>
</div>

app/views/pets/show.html.erb
<p style="color: green"><%= notice %></p>



<p>
  <strong>Nombre:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Raza:</strong>
  <%= @pet.race %>
</p>

<p>
  <strong>Fecha de Nacimiento:</strong>
  <%= @pet.birthdate %>
</p>


<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th>Peso promedio</th>
      <th>Altura promedio</th>
      <th>Peso Máximo</th>
      <th>Altura Máxima</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @pet.avg_weight %></td>
      <td><%= @pet.avg_height %></td>
      <td><%= @pet.max_weight %></td>
      <td><%= @pet.max_height%></td>
    </tr>
  </tbody>
</table>

<div>
  <%= link_to "Editar", edit_pet_path(@pet) %> |
  <%= link_to "Volver a mascotas", pets_path %>

  <%= button_to "Eliminar", @pet, method: :delete, data: { confirm: 'Está seguro?' } %>
</div>